
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

ignored = ["github.com/gopherjs/gopherjs"]

[[constraint]]
  name = "github.com/FlashbackSRS/flashback-model"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  name = "github.com/flimzy/diff"
  version = "0.1.2"

[[constraint]]
  name = "github.com/flimzy/go-cordova"

[[constraint]]
  name = "github.com/flimzy/goweb"

[[constraint]]
  name = "github.com/flimzy/jqeventrouter"

[[constraint]]
  branch = "master"
  name = "github.com/flimzy/kivik"

[[constraint]]
  name = "github.com/flimzy/log"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-kivik/memorydb"

[[constraint]]
  name = "github.com/go-kivik/pouchdb"
  version = "1.0.6"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  name = "github.com/gopherjs/jquery"

[[constraint]]
  name = "github.com/gopherjs/jsbuiltin"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "1.8.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sergi/go-diff"

[[constraint]]
  name = "golang.org/x/text"

[[constraint]]
  name = "honnef.co/go/js/console"
